# Generated by Django 5.0.7 on 2025-01-22 15:45

from django.db import migrations, models
# This class defines a migration, which is a way to change the database schema in Django.
class Migration(migrations.Migration):
    # The dependencies list tells Django that this migration depends on the previous one, "0001_initial".
    dependencies = [
        ("app", "0001_initial"),
    ]

    # The operations list contains the changes we want to make to the database.
    operations = [
        # Here, we are altering a field in the "article" model.
        migrations.AlterField(
            # We specify the model we are changing, which is "article".
            model_name="article",
            # We are changing the "word_count" field in that model.
            name="word_count",
            # We define the new characteristics of this field.
            field=models.IntegerField(blank=True, default=""),
            # This means the field can be left empty (blank=True) and has a default value of an empty string.
        ),
    ]
