# Generated by Django 5.0.7 on 2025-01-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="word_count",
            field=models.IntegerField(blank=True, default=""),
        ),
    ]
