# Generated by Django 5.0.7 on 2025-01-22 17:02
from django.utils import timezone
# We import the timezone module from Django instead of using the vanilla Python time module 
# because Django's timezone provides better support for handling time zones and 
# ensures that we are working with aware datetime objects. This is important for 
# applications that may be used in different time zones, as it helps avoid issues 
# related to daylight saving time and other time-related discrepancies. 
# Using Django's timezone allows us to easily manage and manipulate time in a way 
# that is consistent with the rest of the Django framework.
from django.db import migrations

def create_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()

        if User.objects.exists():
            return
        
        superuser = User.objects.create_superuser(
            username="daria.alekseeva",
            email="daria.alekseeva@slice.com",
            password="app1!",
            last_login=timezone.now()
        )
        superuser.save()

class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_article_word_count"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]




