# Generated by Django 5.0.7 on 2025-01-23 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_auto_20250122_1702"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
